= A Day in Java Developer's Life, with a taste of Kubernetes
:toc:

Deploying your Java application in a Kubernetes cluster could feel like Alice in Wonderland. You keep going down the rabbit hole and don't know how to make that ride comfortable. This repository explains how a Java application consisting of three  microservices can be deployed in a Kubernetes cluster.

== Microservices

The three microservices are:

. `webapp`: Web application microservice calls `greeting` and `name` microservice to generate a greeting for a person.
. `greeting`: A microservice that returns a greeting.
. `name`: A microservice that returns a person’s name based upon `{id}` in the URL.

== Build and Test Services using Maven

. Each microservice is in a different repo:
+
[cols="1,3"]
|====
| `greeting` | https://github.com/arun-gupta/microservices-greeting
| `name` | https://github.com/arun-gupta/microservices-name
| `webapp` | https://github.com/arun-gupta/microservices-webapp
|====
+
. Clone all the repos. Open each one in a separate terminal.
. Run `greeting` service:
+
	mvn wildfly-swarm:run
+
Test:
+
	curl http://localhost:8081/resources/greeting
+
. Run `name` service:
+
	mvn wildfly-swarm:run
+
Test:
+
	curl http://localhost:8082/resources/names
	curl http://localhost:8082/resources/names/1
+
. Run `webapp` service:

	mvn wildfly-swarm:run

. Run the application:

	curl http://localhost:8080/

== Package as Docker image

=== Create Docker Images

`mvn package -Pdocker` for each repo will create the Docker image.

By default, the Docker image name is `arungupta/<service>` where `<service>` is `greeting`, `name` or `webapp`. The image can be created in your repo:

  mvn package -Pdocker -Ddocker.repo=<repo>

By default, the `latest` tag is used for the image. A different tag may be specified as:

  mvn package -Pdocker -Ddocker.tag=<tag>

=== Push Docker Images to Registry

Push Docker images to the registry:

  mvn install -Pdocker

== Test in Local Environment

Kubernetes can be easily enabled on a development machine using Docker for Mac as explained at https://docs.docker.com/docker-for-mac/#kubernetes.

. Configure kubectl CLI for Kubernetes cluster

	kubectl config use-context docker-for-desktop

. Install the Helm CLI:
+
	brew install kubernetes-helm
+
If Helm CLI is already installed then use `brew upgrade kubernetes-helm`.
+
. Install Helm in Kubernetes cluster:
+
	helm init
+
If Helm has already been initialized on the cluster then you may have to upgrade Tiller:
+
	helm init --upgrade
+
. Install the Helm chart:
+
	helm install --name myapp manifests/myapp
+
By default, the `latest` tag for an image is used. Alternatively, a different tag for the image can be used:
+
  helm install --name myapp apps/k8s/helm/myapp --set "docker.tag=<tag>"
+
. Access the application:

  curl http://$(kubectl get svc/myapp-webapp -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

. Delete the Helm chart:

	helm delete --purge myapp

== Attach Debugger

== Istio

. Install and configure:
+
```
curl -L https://github.com/istio/istio/releases/download/0.8.0/istio-0.8.0-osx.tar.gz | tar xzvf -
cd istio-0.8.0
export PATH=$PWD/bin:$PATH
kubectl apply -f install/kubernetes/istio-demo.yaml
```
+
. Verify:
+
```
kubectl get svc -n istio-system
NAME                       TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                               AGE
grafana                    ClusterIP      10.109.62.166    <none>        3000/TCP                                                              43s
istio-citadel              ClusterIP      10.110.20.48     <none>        8060/TCP,9093/TCP                                                     43s
istio-egressgateway        ClusterIP      10.96.67.231     <none>        80/TCP,443/TCP                                                        43s
istio-ingressgateway       LoadBalancer   10.111.113.246   localhost     80:31380/TCP,443:31390/TCP,31400:31400/TCP                            43s
istio-pilot                ClusterIP      10.108.5.61      <none>        15003/TCP,15005/TCP,15007/TCP,15010/TCP,15011/TCP,8080/TCP,9093/TCP   43s
istio-policy               ClusterIP      10.106.61.144    <none>        9091/TCP,15004/TCP,9093/TCP                                           43s
istio-sidecar-injector     ClusterIP      10.100.87.140    <none>        443/TCP                                                               43s
istio-statsd-prom-bridge   ClusterIP      10.101.163.79    <none>        9102/TCP,9125/UDP                                                     43s
istio-telemetry            ClusterIP      10.97.85.21      <none>        9091/TCP,15004/TCP,9093/TCP,42422/TCP                                 43s
prometheus                 ClusterIP      10.111.107.203   <none>        9090/TCP                                                              43s
servicegraph               ClusterIP      10.103.81.16     <none>        8088/TCP                                                              43s
tracing                    LoadBalancer   10.98.140.25     <pending>     80:30349/TCP                                                          36s
zipkin                     ClusterIP      10.106.229.33    <none>        9411/TCP                                                              36s
```
+
. 

== Kubernetes Cluster on AWS

=== Kops Cluster

==== Outside China

. Set AZs: `export AWS_AVAILABILITY_ZONES="$(aws ec2 describe-availability-zones --query 'AvailabilityZones[].ZoneName' --output text | awk -v OFS="," '$1=$1')"`
. Set state store: `export KOPS_STATE_STORE=s3://kubernetes-aws-io`
. Create cluster:

  kops create cluster \
  	--zones ${AWS_AVAILABILITY_ZONES} \
  	--master-count 1 \
  	--node-count 5 \
  	--name cluster.k8s.local \
  	--yes

. Enable admission controllers as explained at https://istio.io/docs/setup/kubernetes/quick-start/#aws-w-kops

==== In China

https://github.com/kubernetes/kops/blob/master/docs/aws-china.md

. Configure China region for `aws` CLI:

	$ aws configure
	AWS Access Key ID [********************]: **********
	AWS Secret Access Key [********************]: **********
	Default region name [us-west-2]: cn-north-1
	Default output format [None]: 

. Set region: `export AWS_REGION=cn-north-1`
. Create bucket: `aws s3api create-bucket --bucket kubernetes-aws-china --create-bucket-configuration LocationConstraint=$AWS_REGION`
. Set state store: `export KOPS_STATE_STORE=s3://kubernetes-aws-china`
. Set AZs: `export AWS_AVAILABILITY_ZONES="$(aws ec2 describe-availability-zones --query 'AvailabilityZones[].ZoneName' --output text | awk -v OFS="," '$1=$1')"`

=== EKS Cluster

== Migrate from Dev to Prod

== Service Visibility using Istio

== Deployment Pipeline

== Alexa Skill to Scale the Application

== A/B Deployment

