= A Day in Java Developer's Life, with a taste of Kubernetes
:toc:

Deploying your Java application in a Kubernetes cluster could feel like Alice in Wonderland. You keep going down the rabbit hole and don't know how to make that ride comfortable. This repository explains how a Java application consisting of three  microservices can be deployed in a Kubernetes cluster.

== Microservices

The three microservices are:

. `webapp`: Web application microservice calls `greeting` and `name` microservice to generate a greeting for a person.
. `greeting`: A microservice that returns a greeting.
. `name`: A microservice that returns a person’s name based upon `{id}` in the URL.

== Build and Test Services using Maven

. Each microservice is in a different repo:
+
[cols="1,3"]
|====
| `greeting` | https://github.com/arun-gupta/microservices-greeting
| `name` | https://github.com/arun-gupta/microservices-name
| `webapp` | https://github.com/arun-gupta/microservices-webapp
|====
+
. Clone all the repos. Open each one in a separate terminal.
. Run `greeting` service: `mvn wildfly-swarm:run`
.. Optionally test: `curl http://localhost:8081/resources/greeting`
. Run `name` service: `mvn wildfly-swarm:run`
.. Optionally test:
... `curl http://localhost:8082/resources/names`
... `curl http://localhost:8082/resources/names/1`
. Run `webapp` service: `mvn wildfly-swarm:run`
. Run the application: `curl http://localhost:8080/`

== Package as Docker image

=== Create Docker Images

`mvn package -Pdocker` for each repo will create the Docker image.

By default, the Docker image name is `arungupta/<service>` where `<service>` is `greeting`, `name` or `webapp`. The image can be created in your repo:

  mvn package -Pdocker -Ddocker.repo=<repo>

By default, the `latest` tag is used for the image. A different tag may be specified as:

  mvn package -Pdocker -Ddocker.tag=<tag>

=== Push Docker Images to Registry

Push Docker images to the registry:

  mvn install -Pdocker

== Test in Local Environment

Kubernetes can be easily enabled on a development machine using Docker for Mac as explained at https://docs.docker.com/docker-for-mac/#kubernetes.

. Configure kubectl CLI for Kubernetes cluster

	kubectl config use-context docker-for-desktop

. Install the Helm CLI:
+
	brew install kubernetes-helm
+
If Helm CLI is already installed then use `brew upgrade kubernetes-helm`.
+
. Install Helm in Kubernetes cluster:
+
	helm init
+
If Helm has already been initialized on the cluster then you may have to upgrade Tiller:
+
	helm init --upgrade
+
. Install the Helm chart:
+
	helm install --name myapp manifests/myapp
+
By default, the `latest` tag for an image is used. Alternatively, a different tag for the image can be used:
+
  helm install --name myapp apps/k8s/helm/myapp --set "docker.tag=<tag>"
+
. Access the application:
+
  curl http://$(kubectl get svc/myapp-webapp -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+
. Delete the Helm chart:

	helm delete --purge myapp


== Attach Debugger

== Service Visibility using Istio

== Kubernetes Cluster on AWS

== Migrate from Dev to Prod

== Deployment Pipeline

== Alexa Skill to Scale the Application

== A/B Deployment

